### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by snehashisc** [bradtraversy/angular60#1]
Hi after npm install I get the following error. Can one pls check and rectify the issue?
![issue npm](https://cloud.githubusercontent.com/assets/6266092/21652252/fbb4f95a-d2d1-11e6-8adc-cc51878538a8.PNG)

**Comment by kylekwon** [comment]
Please reset "protractor": "4.0.14" in the "package.json" file.

**Comment by snehashisc** [comment]
The issue got resolved.
This solution works for me. Change package.json:
"start": "tsc && concurrently "tsc -w" "lite-server" ",
to:
"start": "concurrently "tsc -w" "lite-server" ",
and test: npm start
